### ISSUE TITLE
I am not getting the Torchscript models can you please help me, how can I access that

### ISSUE THREAD

**Issue by uksamarth** [ElenaRyumina/EMO-AffectNetModel#3]
All [tensorflow models](https://drive.google.com/drive/u/0/folders/12aZyWV7QSDpgYH-ZgyvFtR0GA-fXAiHc) have been converted to [TorchScript models](https://drive.google.com/drive/u/0/folders/12FMeRQABp7zXvAygofQRk75mFiPVwZNQ).

**Comment by ElenaRyumina** [comment]
Hello @uksamarth. 

Thank you for reporting this issue. Model links have been updated.

**Comment by uksamarth** [comment]
Thank you @ElenaRyumina for solving the issue
