### ISSUE TITLE
torch model

### ISSUE THREAD

**Issue by panagiotidi** [ElenaRyumina/EMO-AffectNetModel#4]
Do you have the torch model structure somewhere so that someone can load it directly from the pth file??

**Comment by ElenaRyumina** [comment]
Hi @panagiotidi,

Please refer to the link https://huggingface.co/ElenaRyumina/face_emotion_recognition/blob/main/run_webcam.ipynb, there you will find the model structure. And also use the weights shared on huggingface.

**Comment by panagiotidi** [comment]
Thank you very much!
