### ISSUE TITLE
Facing issues with keras.utils . Could you please add a requirements.txt file? 

### ISSUE THREAD

**Issue by siripiripiri** [ElenaRyumina/EMO-AffectNetModel#5]
When I run the python file `run.py`

errors: 
```

ImportError: cannot import name 'layer_utils' from 'keras.utils' 

ModuleNotFoundError: No module named 'keras.utils.data_utils'

```
My package versions: 

`keras==3.4.1`
`tensorflow==2.17.0`

**Comment by ElenaRyumina** [comment]
Dear @siripiripiri,

Thank you for pointing out the error. The error was that tensorflow==2.17.0 is not compatible with keras-vggface==0.6. To resolve this, we removed the reference to keras-vggface from our code. The repository has been updated, in particular run.py, requirements.txt and files in the functions folder. Everything should now work correctly.

**Comment by siripiripiri** [comment]
@ElenaRyumina Thank You so much! That resolves it.
